#spring:
# config:
#  activate:
#   on-profile: "qa"

build:
  version: "2.0"
  
accounts:
  message: "Welcome to QA "
  contactDetails:
    name: "abcd2"
    email: "abcd2@.com"
  onCallSuppport:
    -11111111
    -22222222